export const CONST = {
  MIN_MAP_X : -100,
  MAX_MAP_X : 100,
  MIN_MAP_Z : -100,
  MAX_MAP_Z : 100,
  MIN_Y : 0,
  WALL_BOUNCE_FACTOR : 0.5,
  FLOOR_BOUNCE_FACTOR : 0.6,
  USER_JUMP_VEL : 0.2,
  USER_SHOOT_DELAY : 5, //ms

  USER_ROTATION_SPEED_X : 0.003,
  USER_ROTATION_SPEED_Y : 0.003,
  USER_FWD_MOVE_SPEED : 0.3,
  USER_SIDE_MOVE_SPEED : 0.15,
  USER_BACK_MOVE_SPEED : 0.15,

  POWERUP_TIME : 5 * 1000,
  SNOWBALL_CHARGE_FACTOR : 50,

  WEBSOCKET_SEND_MIN_DELAY : 30 //ms
}